/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    AudioPack: typeof import('./src/components/visual-editor/settings/AudioPack.vue')['default']
    AvailableVersions: typeof import('./src/components/AvailableVersions.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BonusFeature: typeof import('./src/components/visual-editor/settings/BonusFeature.vue')['default']
    Button: typeof import('primevue/button')['default']
    CanvasCustomization: typeof import('./src/components/visual-editor/settings/CanvasCustomization.vue')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorPicker: typeof import('./src/components/visual-editor/settings/ColorPicker.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteFileDialog: typeof import('./src/components/dialogs/DeleteFileDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EngineSimulator: typeof import('./src/components/simulation-dashboard/EngineSimulator.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProfileMenu: typeof import('./src/components/layout/ProfileMenu.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ReelLayout: typeof import('./src/components/visual-editor/settings/ReelLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    SymbolsTheme: typeof import('./src/components/visual-editor/settings/SymbolsTheme.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TimingsAndBetting: typeof import('./src/components/visual-editor/settings/TimingsAndBetting.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ViewEditDialog: typeof import('./src/components/dialogs/ViewEditDialog.vue')['default']
    VisualAdjuster: typeof import('./src/components/visual-editor/VisualAdjuster.vue')['default']
    Winlines: typeof import('./src/components/visual-editor/settings/Winlines.vue')['default']
    WinlinesEditor: typeof import('./src/components/visual-editor/settings/WinlinesEditor.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
